### ISSUE TITLE
Section 6 Hurricane Ian Figure 6.1 Video

### ISSUE THREAD

**Issue by katiepetrinec** [GTMNERR/swmp-quarter-report#20]
Not sure if you intended for the video to start automatically or not. Just wanted to let you know that I had to click on the video box or link for it to play. 

If the intent is to not have open automatically. I suggest maybe having the video open in another window or if possible, have an option to close the video because you have to select the back arrow to return to the main text.

**Comment by skdunnigan** [comment]
@katiepetrinec so, I think having to click on it is due to the "lightbox" extension I have running on this report that allows us to click on the plots and images to open them up on the entire page. It seems to apply to the video in that you have to click on it to play it now. When you click on it on my computer, I was able to "X" close out of it in the upper righthand corner of the window. Hopefully it happens like that for you?
I am not quite sure how to fix this to "ignore" the lightbox extension as I do want that for the figures on this page...
